(function (global) {
  "use strict";

  const simulationNodes = {
    sim_1: {
      id: "sim_1",
      type: "conversation",
      category: "Greeting",
      sceneTitle: "Clinic Intake",
      sceneContext: "A patient arrives at the clinic looking uncomfortable. Start with a calm greeting.",
      speaker: "Nurse",
      emotionalTone: "calm and welcoming",
      botTextEnglish: "The patient has just arrived. Begin the medical conversation with a polite greeting.",
      botTextSpanish: "Buenos días, ¿cómo se siente?",
      patientLineEnglish: "Good morning. I do not feel well.",
      patientLineSpanish: "Buenos días. No me siento bien.",
      learnerInstruction: "Greet the patient and ask how they feel.",
      expectedResponses: ["buenos dias como se siente"],
      acceptedVariants: ["buenos días cómo se siente", "como se siente", "buenos dias como esta"],
      pronunciationFocus: "Clear vowel sounds in días and siente.",
      coachingTip: "Keep the question smooth: buenos días, cómo se siente.",
      successFeedback: "Nice opening. The patient would understand your greeting and question.",
      partialFeedback: "Good start. The greeting was understandable, but complete the question with cómo se siente.",
      failureFeedback: "Let's slow down the opening question before the patient continues.",
      remediationPrompt: "Repeat the full greeting: Buenos días, ¿cómo se siente?",
      successNode: "sim_2",
      clarificationNode: "sim_1",
      retryNode: "sim_1",
      fallbackNode: "sim_2",
      maxAttempts: 3,
      difficultyLevel: 1
    },
    sim_2: {
      id: "sim_2",
      type: "conversation",
      category: "Symptoms",
      sceneTitle: "Pain Report",
      sceneContext: "The same patient now points to the chest and reports pain.",
      speaker: "Patient",
      emotionalTone: "worried",
      botTextEnglish: "The patient says they have chest pain. Confirm the symptom in Spanish.",
      botTextSpanish: "Tengo dolor en el pecho.",
      patientLineEnglish: "I have pain in my chest.",
      patientLineSpanish: "Tengo dolor en el pecho.",
      learnerInstruction: "Confirm that the patient has chest pain.",
      expectedResponses: ["tiene dolor en el pecho"],
      acceptedVariants: ["usted tiene dolor en el pecho", "dolor en el pecho", "tiene dolor"],
      pronunciationFocus: "The final R in dolor and the CH sound in pecho.",
      coachingTip: "Make dolor clear and do not drop en el pecho.",
      successFeedback: "Good. You identified the chest pain clearly.",
      partialFeedback: "I heard part of the symptom. Try including the full phrase: dolor en el pecho.",
      failureFeedback: "The patient needs you to confirm the symptom clearly.",
      remediationPrompt: "Repeat: Tiene dolor en el pecho.",
      successNode: "sim_3",
      clarificationNode: "sim_2",
      retryNode: "sim_2",
      fallbackNode: "sim_3",
      maxAttempts: 3,
      difficultyLevel: 1
    },
    sim_3: {
      id: "sim_3",
      type: "conversation",
      category: "Assessment",
      sceneTitle: "Pain Check",
      sceneContext: "You need to learn whether the pain is strong or mild before deciding next steps.",
      speaker: "Nurse",
      emotionalTone: "focused",
      botTextEnglish: "Ask a short follow-up question about the pain level.",
      botTextSpanish: "¿Tiene mucho dolor?",
      patientLineEnglish: "Yes, it hurts a lot.",
      patientLineSpanish: "Sí, tengo mucho dolor.",
      learnerInstruction: "Ask whether the patient has a lot of pain.",
      expectedResponses: ["tiene mucho dolor"],
      acceptedVariants: ["usted tiene mucho dolor", "tiene dolor fuerte", "mucho dolor"],
      pronunciationFocus: "The soft CH in mucho and final R in dolor.",
      coachingTip: "Say mucho clearly before dolor so the question is complete.",
      successFeedback: "Strong follow-up. You asked a useful clinical question.",
      partialFeedback: "You were close. I understood pain, but the intensity word mucho matters here.",
      failureFeedback: "Let's make the follow-up question clearer.",
      remediationPrompt: "Repeat: ¿Tiene mucho dolor?",
      successNode: "sim_4",
      clarificationNode: "sim_3",
      retryNode: "sim_3",
      fallbackNode: "sim_4",
      maxAttempts: 3,
      difficultyLevel: 2
    },
    sim_4: {
      id: "sim_4",
      type: "conversation",
      category: "Symptoms",
      sceneTitle: "Fever Concern",
      sceneContext: "The patient feels warm and may have a fever.",
      speaker: "Patient",
      emotionalTone: "uncomfortable",
      botTextEnglish: "The patient says they feel hot. Ask if they have a fever.",
      botTextSpanish: "¿Tiene fiebre?",
      patientLineEnglish: "I feel very warm.",
      patientLineSpanish: "Me siento muy caliente.",
      learnerInstruction: "Ask the patient if they have fever.",
      expectedResponses: ["tiene fiebre"],
      acceptedVariants: ["usted tiene fiebre", "fiebre", "tiene fiebre alta"],
      pronunciationFocus: "The first syllable in fiebre: FIE-bre.",
      coachingTip: "Keep fiebre two clear syllables, not one rushed sound.",
      successFeedback: "Good clinical question. The patient can answer about fever now.",
      partialFeedback: "I heard fiebre, but the question needs tiene fiebre.",
      failureFeedback: "Let's ask the fever question more clearly.",
      remediationPrompt: "Repeat: ¿Tiene fiebre?",
      successNode: "sim_5",
      clarificationNode: "sim_4",
      retryNode: "sim_4",
      fallbackNode: "sim_5",
      maxAttempts: 3,
      difficultyLevel: 2
    },
    sim_5: {
      id: "sim_5",
      type: "conversation",
      category: "Symptoms",
      sceneTitle: "Headache Added",
      sceneContext: "The patient adds another symptom: headache.",
      speaker: "Patient",
      emotionalTone: "tired",
      botTextEnglish: "The patient says: Me duele la cabeza. That means: My head hurts. Ask where the pain is.",
      botTextSpanish: "¿Dónde le duele?",
      patientLineEnglish: "My head hurts.",
      patientLineSpanish: "Me duele la cabeza.",
      learnerInstruction: "Ask where it hurts.",
      expectedResponses: ["donde le duele"],
      acceptedVariants: ["dónde le duele", "donde duele", "que le duele"],
      pronunciationFocus: "The D sounds in dónde and duele.",
      coachingTip: "Make it a question: dónde le duele.",
      successFeedback: "Good. You kept the assessment moving with a useful question.",
      partialFeedback: "Good attempt. The word duele was there, but the question needs dónde.",
      failureFeedback: "Let's slow down the question about location.",
      remediationPrompt: "Repeat: ¿Dónde le duele?",
      successNode: "sim_6",
      clarificationNode: "sim_5",
      retryNode: "sim_5",
      fallbackNode: "sim_6",
      maxAttempts: 3,
      difficultyLevel: 2
    },
    sim_6: {
      id: "sim_6",
      type: "conversation",
      category: "Care",
      sceneTitle: "Call The Doctor",
      sceneContext: "Pain and fever together require escalation to a clinician.",
      speaker: "Nurse",
      emotionalTone: "reassuring",
      botTextEnglish: "Now reassure the patient and say you are going to call the doctor.",
      botTextSpanish: "Voy a llamar al médico.",
      patientLineEnglish: "Do I need a doctor?",
      patientLineSpanish: "¿Necesito un médico?",
      learnerInstruction: "Tell the patient you are going to call the doctor.",
      expectedResponses: ["voy a llamar al medico"],
      acceptedVariants: ["voy a llamar al médico", "llamo al medico", "voy llamar medico"],
      pronunciationFocus: "The accented first syllable in médico.",
      coachingTip: "Keep the full action clear: voy a llamar al médico.",
      successFeedback: "Excellent. That response gives the patient clear next steps.",
      partialFeedback: "I understood médico. Try saying the full action: voy a llamar.",
      failureFeedback: "The patient needs a clear care plan.",
      remediationPrompt: "Repeat: Voy a llamar al médico.",
      successNode: "sim_7",
      clarificationNode: "sim_6",
      retryNode: "sim_6",
      fallbackNode: "sim_7",
      maxAttempts: 3,
      difficultyLevel: 3
    },
    sim_7: {
      id: "sim_7",
      type: "conversation",
      category: "Emergency",
      sceneTitle: "Breathing Changes",
      sceneContext: "The patient suddenly says it is hard to breathe.",
      speaker: "Patient",
      emotionalTone: "anxious",
      botTextEnglish: "The situation is becoming urgent. The patient says they cannot breathe well.",
      botTextSpanish: "No puedo respirar bien.",
      patientLineEnglish: "I cannot breathe well.",
      patientLineSpanish: "No puedo respirar bien.",
      learnerInstruction: "Ask if the patient can breathe.",
      expectedResponses: ["puede respirar"],
      acceptedVariants: ["usted puede respirar", "puede respirar bien", "puede respirar ahora"],
      pronunciationFocus: "The final R in respirar.",
      coachingTip: "Slow down respirar and emphasize the final R.",
      successFeedback: "Good urgent assessment. You checked breathing clearly.",
      partialFeedback: "I heard respirar. Try adding puede so it becomes the question.",
      failureFeedback: "This is urgent, so the breathing question must be clear.",
      remediationPrompt: "Repeat: ¿Puede respirar?",
      successNode: "sim_8",
      clarificationNode: "sim_7",
      retryNode: "sim_7",
      fallbackNode: "sim_8",
      maxAttempts: 3,
      difficultyLevel: 3
    },
    sim_8: {
      id: "sim_8",
      type: "conversation",
      category: "Emergency",
      sceneTitle: "Emergency Identified",
      sceneContext: "Chest pain with breathing difficulty should be treated as an emergency.",
      speaker: "Nurse",
      emotionalTone: "urgent but controlled",
      botTextEnglish: "Identify the situation for the team. Say that this is an emergency.",
      botTextSpanish: "Es una emergencia.",
      patientLineEnglish: "I am scared.",
      patientLineSpanish: "Tengo miedo.",
      learnerInstruction: "Say that this is an emergency.",
      expectedResponses: ["es una emergencia"],
      acceptedVariants: ["una emergencia", "emergencia", "esto es una emergencia"],
      pronunciationFocus: "Four clear syllables in emergencia: e-mer-GEN-cia.",
      coachingTip: "Do not rush emergencia; make the middle sound clear.",
      successFeedback: "Correct. You recognized the escalation clearly.",
      partialFeedback: "I heard emergencia. Add es una to make the statement complete.",
      failureFeedback: "Let's identify the emergency clearly.",
      remediationPrompt: "Repeat: Es una emergencia.",
      successNode: "sim_9",
      clarificationNode: "sim_8",
      retryNode: "sim_8",
      fallbackNode: "sim_9",
      maxAttempts: 3,
      difficultyLevel: 3
    },
    sim_9: {
      id: "sim_9",
      type: "conversation",
      category: "Support",
      sceneTitle: "Immediate Help",
      sceneContext: "The patient is frightened and needs reassurance while help is called.",
      speaker: "Nurse",
      emotionalTone: "supportive",
      botTextEnglish: "Reassure the patient. Tell them help is coming.",
      botTextSpanish: "La ayuda viene.",
      patientLineEnglish: "Please help me.",
      patientLineSpanish: "Por favor, ayúdeme.",
      learnerInstruction: "Tell the patient that help is coming.",
      expectedResponses: ["la ayuda viene"],
      acceptedVariants: ["ayuda viene", "viene ayuda", "la ayuda esta viniendo"],
      pronunciationFocus: "The Y sound in ayuda.",
      coachingTip: "Ayuda begins with a strong ah sound: ah-YU-da.",
      successFeedback: "Good reassurance. The patient hears that help is coming.",
      partialFeedback: "I heard ayuda. Try the full reassuring sentence: la ayuda viene.",
      failureFeedback: "Let's make the reassurance clearer.",
      remediationPrompt: "Repeat: La ayuda viene.",
      successNode: "sim_10",
      clarificationNode: "sim_9",
      retryNode: "sim_9",
      fallbackNode: "sim_10",
      maxAttempts: 3,
      difficultyLevel: 3
    },
    sim_10: {
      id: "sim_10",
      type: "conversation",
      category: "Support",
      sceneTitle: "Comfort While Waiting",
      sceneContext: "The patient is waiting for the doctor and asks for water.",
      speaker: "Patient",
      emotionalTone: "relieved but weak",
      botTextEnglish: "The patient asks for water while waiting. Respond supportively.",
      botTextSpanish: "¿Necesita agua?",
      patientLineEnglish: "I need water, please.",
      patientLineSpanish: "Necesito agua, por favor.",
      learnerInstruction: "Ask if the patient needs water.",
      expectedResponses: ["necesita agua"],
      acceptedVariants: ["usted necesita agua", "necesita agua por favor", "quiere agua"],
      pronunciationFocus: "The open AH sound at the start of agua.",
      coachingTip: "Let agua start clearly and softly connect it to necesita.",
      successFeedback: "Nice finish. You supported the patient while help was on the way.",
      partialFeedback: "Good attempt. Make necesita agua clear as one supportive question.",
      failureFeedback: "Let's finish with a clear supportive question.",
      remediationPrompt: "Repeat: ¿Necesita agua?",
      successNode: null,
      clarificationNode: "sim_10",
      retryNode: "sim_10",
      fallbackNode: null,
      maxAttempts: 3,
      difficultyLevel: 3
    }
  };

  global.SimulationData = {
    startNodeId: "sim_1",
    orderedNodeIds: Object.keys(simulationNodes),
    simulationNodes
  };
})(window);
